# Generated by Django 4.1.5 on 2023-01-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
