# Generated by Django 4.1.5 on 2023-01-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_bookcard_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='status',
            field=models.CharField(choices=[(1, 'taken'), (2, 'available')], max_length=1),
        ),
    ]
