# Generated by Django 4.1.5 on 2023-02-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSpecial',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.comment')),
            ],
            bases=('blog.comment',),
        ),
    ]
